'use strict';

module.exports = Object.freeze({
    "31": "Objects are not valid as a React child (found: %s). If you meant to render a collection of children, use an array instead.",
    "33": "getNodeFromInstance: Invalid argument.",
    "60": "Can only set one of `children` or `props.dangerouslySetInnerHTML`.",
    "61": "`props.dangerouslySetInnerHTML` must be in the form `{__html: ...}`. Please visit https://react.dev/link/dangerously-set-inner-html for more information.",
    "62": "The `style` prop expects a mapping from style properties to values, not a string. For example, style={{marginRight: spacing + 'em'}} when using JSX.",
    "90": "ReactDOMInput: Mixing React and non-React radio inputs with the same `name` is not supported.",
    "91": "`dangerouslySetInnerHTML` does not make sense on <textarea>.",
    "92": "If you supply `defaultValue` on a <textarea>, do not pass children.",
    "93": "<textarea> can only have at most one child.",
    "130": "Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: %s.%s",
    "137": "%s is a void element tag and must neither have `children` nor use `dangerouslySetInnerHTML`.",
    "150": "An object is not an iterable. This error is likely caused by a bug in React. Please file an issue.",
    "151": "An iterable object provided no iterator.",
    "153": "Resuming work not yet implemented.",
    "156": "Unknown unit of work tag (%s). This error is likely caused by a bug in React. Please file an issue.",
    "160": "Expected to find a host parent. This error is likely caused by a bug in React. Please file an issue.",
    "161": "Invalid host parent fiber. This error is likely caused by a bug in React. Please file an issue.",
    "162": "This should have a text node initialized. This error is likely caused by a bug in React. Please file an issue.",
    "163": "This unit of work tag should not have side-effects. This error is likely caused by a bug in React. Please file an issue.",
    "166": "We must have new props for new mounts. This error is likely caused by a bug in React. Please file an issue.",
    "177": "Cannot commit the same tree as before. This error is likely caused by a bug in React. Please file an issue.",
    "185": "Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.",
    "188": "Unable to find node on an unmounted component.",
    "189": "Child was not found in either parent set. This indicates a bug in React related to the return pointer. Please file an issue.",
    "190": "Return fibers should always be each others' alternates. This error is likely caused by a bug in React. Please file an issue.",
    "191": "Invalid argument passed as callback. Expected a function. Instead received: %s",
    "231": "Expected `%s` listener to be a function, instead got a value of `%s` type.",
    "268": "Argument appears to not be a ReactComponent. Keys: %s",
    "284": "Expected ref to be a function, an object returned by React.createRef(), or undefined/null.",
    "299": "Target container is not a DOM element.",
    "300": "Rendered fewer hooks than expected. This may be caused by an accidental early return statement.",
    "301": "Too many re-renders. React limits the number of renders to prevent an infinite loop.",
    "308": "Context can only be read while React is rendering. In classes, you can read it in the render method or getDerivedStateFromProps. In function components, you can read it directly in the function body, but not inside Hooks like useReducer() or useMemo().",
    "310": "Rendered more hooks than during the previous render.",
    "311": "Should have a queue. You are likely calling Hooks conditionally, which is not allowed. (https://react.dev/link/invalid-hook-call)",
    "314": "Pinged unknown suspense boundary type. This is probably a bug in React.",
    "317": "Expected to have a hydrated suspense instance. This error is likely caused by a bug in React. Please file an issue.",
    "318": "A dehydrated suspense component was completed without a hydrated node. This is probably a bug in React.",
    "321": "Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:\n1. You might have mismatching versions of React and the renderer (such as React DOM)\n2. You might be breaking the Rules of Hooks\n3. You might have more than one copy of React in the same app\nSee https://react.dev/link/invalid-hook-call for tips about how to debug and fix this problem.",
    "327": "Should not already be working.",
    "329": "Unknown root exit status.",
    "331": "Cannot flush passive effects while already rendering.",
    "340": "Threw in newly mounted dehydrated component. This is likely a bug in React. Please file an issue.",
    "341": "We just came from a parent so we must have had a parent. This is a bug in React.",
    "345": "Root did not complete. This is a bug in React.",
    "349": "Expected a work-in-progress root. This is a bug in React. Please file an issue.",
    "387": "Should have a current fiber. This is a bug in React.",
    "407": "Missing getServerSnapshot, which is required for server-rendered content. Will revert to client rendering.",
    "409": "Cannot update an unmounted root.",
    "418": "Hydration failed because the server rendered %s didn't match the client. As a result this tree will be regenerated on the client. This can happen if a SSR-ed Client Component used:\n\n- A server/client branch `if (typeof window !== 'undefined')`.\n- Variable input such as `Date.now()` or `Math.random()` which changes each time it's called.\n- Date formatting in a user's locale which doesn't match the server.\n- External changing data without sending a snapshot of it along with the HTML.\n- Invalid HTML tag nesting.\n\nIt can also happen if the client has a browser extension installed which messes with the HTML before React loaded.\n\nhttps://react.dev/link/hydration-mismatch%s",
    "419": "The server could not finish this Suspense boundary, likely due to an error during server rendering. Switched to client rendering.",
    "422": "There was an error while hydrating but React was able to recover by instead client rendering from the nearest Suspense boundary.",
    "423": "There was an error while hydrating but React was able to recover by instead client rendering the entire root.",
    "424": "This root received an early update, before anything was able hydrate. Switched the entire root to client rendering.",
    "435": "Unexpected Suspense handler tag (%s). This is a bug in React.",
    "438": "An unsupported type was passed to use(): %s",
    "440": "A function wrapped in useEffectEvent can't be called during rendering.",
    "443": "acquireResource encountered a resource type it did not expect: \"%s\". this is a bug in React.",
    "444": "getResource encountered a type it did not expect: \"%s\". this is a bug in React.",
    "446": "\"resourceRoot\" was expected to exist. This is a bug in React.",
    "451": "resolveSingletonInstance was called with an element type that is not supported. This is a bug in React.",
    "452": "React expected an <html> element (document.documentElement) to exist in the Document but one was not found. React never removes the documentElement for any Document it renders into so the cause is likely in some other script running on this page.",
    "453": "React expected a <head> element (document.head) to exist in the Document but one was not found. React never removes the head for any Document it renders into so the cause is likely in some other script running on this page.",
    "454": "React expected a <body> element (document.body) to exist in the Document but one was not found. React never removes the body for any Document it renders into so the cause is likely in some other script running on this page.",
    "459": "Expected a suspended thenable. This is a bug in React. Please file an issue.",
    "460": "Suspense Exception: This is not a real error! It's an implementation detail of `use` to interrupt the current render. You must either rethrow it immediately, or move the `use` call outside of the `try/catch` block. Capturing without rethrowing will lead to unexpected behavior.\n\nTo handle async errors, wrap your component in an error boundary, or call the promise's `.catch` method and pass the result to `use`.",
    "461": "This is not a real error. It's an implementation detail of React's selective hydration feature. If this leaks into userspace, it's a bug in React. Please file an issue.",
    "462": "Unexpected SuspendedReason. This is a bug in React.",
    "467": "Update hook called on initial render. This is likely a bug in React. Please file an issue.",
    "468": "getNodesForType encountered a type it did not expect: \"%s\". This is a bug in React.",
    "474": "Suspense Exception: This is not a real error, and should not leak into userspace. If you're seeing this, it's likely a bug in React.",
    "475": "Internal React Error: suspendedState null when it was expected to exists. Please report this as a React bug.",
    "476": "Expected the form instance to be a HostComponent. This is a bug in React.",
    "479": "Cannot update optimistic state while rendering.",
    "482": "An unknown Component is an async Client Component. Only Server Components can be async at the moment. This error is often caused by accidentally adding `'use client'` to a module that was originally written for the server.",
    "483": "Hooks are not supported inside an async component. This error is often caused by accidentally adding `'use client'` to a module that was originally written for the server.",
    "485": "Cannot update form state while rendering.",
    "519": "Hydration Mismatch Exception: This is not a real error, and should not leak into userspace. If you're seeing this, it's likely a bug in React.",
    "520": "There was an error during concurrent rendering but React was able to recover by instead synchronously rendering the entire root.",
    "522": "Invalid form element. requestFormReset must be passed a form that was rendered by React.",
    "525": "A React Element from an older version of React was rendered. This is not supported. It can happen if:\n- Multiple copies of the \"react\" package is used.\n- A library pre-bundled an old copy of \"react\" or \"react/jsx-runtime\".\n- A compiler tries to \"inline\" JSX instead of using the runtime.",
    "527": "Incompatible React versions: The \"react\" and \"react-dom\" packages must have the exact same version. Instead got:\n  - react:      %s\n  - react-dom:  %s\nLearn more: https://react.dev/warnings/version-mismatch",
    "528": "Expected <link> not to update to be updated to a stylesheet with precedence. Check the `rel`, `href`, and `precedence` props of this component. Alternatively, check whether two different <link> components render in the same slot or share the same key.%s",
    "529": "Expected stylesheet with precedence to not be updated to a different kind of <link>. Check the `rel`, `href`, and `precedence` props of this component. Alternatively, check whether two different <link> components render in the same slot or share the same key.%s",
    "542": "Suspense Exception: This is not a real error! It's an implementation detail of `useActionState` to interrupt the current render. You must either rethrow it immediately, or move the `useActionState` call outside of the `try/catch` block. Capturing without rethrowing will lead to unexpected behavior.\n\nTo handle async errors, wrap your component in an error boundary.",
    "557": "Expected to have a hydrated activity instance. This error is likely caused by a bug in React. Please file an issue.",
    "558": "Client rendering an Activity suspended it again. This is a bug in React."
});
