export const ISOLATED_API_METHODS = Object.freeze([
    'playVibe',
    'play',
    'pause',
    'togglePlayPause',
    'next',
    'previous',
    'setRepeatMode',
    'toggleShuffle',
    'setVolume',
    'setProgress',
    'playTrackById',
    'playPlaylistById',
    'addTrackToQueueById',
    'likeTrack',
    'unlikeTrack',
    'dislikeTrack',
    'undislikeTrack',
    'isTrackLiked',
    'isTrackDisliked',
    'isPlaying',
    'getCurrentTrack',
    'getQueue',
    'getProgress',
    'getDuration',
    'getVolume',
    'getRepeatMode',
    'isShuffle',
    'getDisplayMaxFps',
    'getPlatform',
    'getPremiumStatus',
    'refreshPlayerBar',
] as const)

export const ISOLATED_API_METHOD_SET: ReadonlySet<string> = new Set(ISOLATED_API_METHODS)
