export const WEB_HOST_API_VERSION = 1
export const WEB_HOST_GLOBAL = '__PULSESYNC_WEB_HOST__'
export const ADDON_QUEUE_GLOBAL = '__PULSESYNC_ADDON_QUEUE__'
export const WEB_HOST_ROOT_ID = 'pulsesync-web-host'
export const LEGACY_ASSETS_EVENT = 'PULSESYNC_LEGACY_ASSETS'
export const LEGACY_ASSETS_SNAPSHOT_EVENT = 'PULSESYNC_LEGACY_ASSETS_SNAPSHOT'
export const WEB_HOST_ADDONS_EVENT = 'PULSESYNC_WEBHOST_ADDONS'
export const WEB_HOST_ADDONS_SNAPSHOT_EVENT = 'PULSESYNC_WEBHOST_ADDONS_SNAPSHOT'
